### ISSUE TITLE
ミニファイ化を削除された理由

### ISSUE THREAD

**Issue by dounokouno** [makog/jQuery.flickSimple.js#3]
初めまして。
tagawaと申します。

jQuery.flickSimple.jsにはいつも助けられております。

ぶしつけて大変恐縮でございますが、表題の件に関しまして、ご質問させていただきたいことがございます。

コミットログを拝見しますと、以前はミニファイ化版があったようですが、もしよろしければ削除された理由をご教示いただけますでしょうか？

私もJavaScriptを書くことがあり、makog様がjQuery.flickSimple.jsのミニファイ化版を作らないご事情を是非知りたく思い、issueを立てさせていただきました。

また、私個人的にはミニファイ化版がありますと、ありがたく存じます。

以上でございます。
  それでは、どうぞよろしくお願いいたします。

**Comment by makog** [comment]
tagawa様
jQuery.flickSimpleをご利用いただき、またご質問をいただきありがとうございます。

ミニファイ版についてですが、以前にPull Requestをいただいた方から、ミニファイ版は二次生成物なのでリポジトリには含めない方がいい、というご指摘をいただいたため、削除しました。代わりに、「ダウンロード（下記URL）」にミニファイ版をアップしています。

https://github.com/makog/jQuery.flickSimple.js/downloads

リポジトリにミニファイ版を含めていると、元のコードに手をいれる度にミニファイ版も同時に更新しなければならなくなります。githubは複数人でコードを更新していくことを念頭においたシステムですので、開発者からするとコミットする度に、純粋に面倒なだけの変換作業を強いられることになります（また、ミニファイ版は差分が分かりづらいので、Requestを受けた側も確認が行いづらい、ということもあります）。

利用する側からするとミニファイ版があったほうが便利なので、本来的には開発用のファイル（＝githubレポジトリ）と配布用のファイルは別に提供するのがよいのだと思います。

ちなみに私の場合、ミニファイ版を作るのに以下のサイトを利用しています。

Google Closure Compiler
http://closure-compiler.appspot.com/home

といったところで、ご回答になっていますでしょうか。
よろしくお願いいたします。

**Comment by dounokouno** [comment]
makog様

早速のお返事ありがとうございます。
githubでの開発ポリシー等、大変勉強になります！

とても納得できましたので、後ほどミニファイ版は作らずにpull requestをお送りさせていただきます。
ご確認いただければ幸いでございます。

以上でございます。
それでは、今後ともどうぞよろしくお願いいたします。
